package com.sitepark.ies.userrepository.core.domain.value;

public enum AuditLogAction {
  CREATE,
  UPDATE,
  REMOVE,
  RESTORE,
  ASSIGN_PRIVILEGES,
  UNASSIGN_PRIVILEGES,
  ASSIGN_ROLES,
  UNASSIGN_ROLES,

  BATCH_REMOVE,
  BATCH_ASSIGN_PRIVILEGES,
  BATCH_UNASSIGN_PRIVILEGES,
  BATCH_ASSIGN_ROLES,
  BATCH_UNASSIGN_ROLES,

  REVERT_BATCH_REMOVE,
  REVERT_BATCH_ASSIGN_PRIVILEGES,
  REVERT_BATCH_UNASSIGN_PRIVILEGES,
  REVERT_BATCH_ASSIGN_ROLES,
  REVERT_BATCH_UNASSIGN_ROLES
}
