name: (📡) Verify

on:
  push:
    branches-ignore:
      - 'main'
  workflow_dispatch:

jobs:
  verify:
    uses: sitepark/github-project-workflow/.github/workflows/maven-verify.yml@main
    secrets:
      BOT_PAT: ${{ secrets.BOT_PAT }}

